### Zookeeper Reference
# https://hub.docker.com/r/bitnami/zookeeper
# https://github.com/bitnami/containers/tree/main/bitnami/zookeeper
### Kafka Reference
# https://hub.docker.com/r/bitnami/kafka

version: '2'

networks:
  app-tier:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      ZOO_SERVER_ID: 1
      ZOO_PORT_NUMBER: 2181
      ZOO_TICK_TIME: 2000
      ZOO_INIT_LIMIT: 10
      ZOO_SYNC_LIMIT: 5
      ALLOW_ANONYMOUS_LOGIN: yes
    volumes:
      - ${BASE_DIR}/zookeeper:/bitnami/zookeeper
      - ${BASE_DIR}/zookeeper/zoo.cfg:/opt/bitnami/zookeeper/conf/zoo.cfg
    ports:
      - '2181:2181'
    networks:
      - app-tier

  kdfka:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - ${BASE_DIR}/kafka:/bitnami/kafka
#      - ${BASE_DIR}/kafka/config:/opt/bitnami/kafka/config
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    networks:
      - app-tier