version: '2'

networks:
  app-tier:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:3.7.1'
    environment:
      - ZOO_SERVER_ID=1
      - ZOO_PORT_NUMBER=2181
      - ZOO_TICK_TIME=2000
      - ZOO_INIT_LIMIT=10
      - ZOO_SYNC_LIMIT=5
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - ${BASE_DIR}/zookeeper/data:/bitnami
      - ${BASE_DIR}/zookeeper/config/zoo.cfg:/opt/bitnami/zookeeper/conf/zoo.cfg
    ports:
      - "2181:2181"
    networks:
      - app-tier

  kafka1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:19092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka1:9092,EXTERNAL://localhost:19092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
    volumes:
      - ${BASE_DIR}/kafka/data1:/bitnami
      - ${BASE_DIR}/kafka/config/producer.properties:/opt/bitnami/kafka/config/producer.properties
      - ${BASE_DIR}/kafka/config/consumer.properties:/opt/bitnami/kafka/config/consumer.properties
      - ${BASE_DIR}/kafka/config/connect-distributed.properties:/opt/bitnami/kafka/config/connect-distributed.properties
      - ${BASE_DIR}/kafka/config/connect-dir-source.properties:/opt/bitnami/kafka/config/connect-dir-source.properties
    ports:
      - '19092:19092'
    depends_on:
      - zookeeper
    networks:
      - app-tier

  kafka2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka2:9092,EXTERNAL://localhost:29092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
    volumes:
      - ${BASE_DIR}/kafka/data2:/bitnami
      - ${BASE_DIR}/kafka/config/producer.properties:/opt/bitnami/kafka/config/producer.properties
      - ${BASE_DIR}/kafka/config/consumer.properties:/opt/bitnami/kafka/config/consumer.properties
      - ${BASE_DIR}/kafka/config/connect-distributed.properties:/opt/bitnami/kafka/config/connect-distributed.properties
      - ${BASE_DIR}/kafka/config/connect-dir-source.properties:/opt/bitnami/kafka/config/connect-dir-source.properties
    ports:
      - '29092:29092'
    depends_on:
      - zookeeper
    networks:
      - app-tier

  kafka3:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:39092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka3:9092,EXTERNAL://localhost:39092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
    volumes:
      - ${BASE_DIR}/kafka/data3:/bitnami
      - ${BASE_DIR}/kafka/config/producer.properties:/opt/bitnami/kafka/config/producer.properties
      - ${BASE_DIR}/kafka/config/consumer.properties:/opt/bitnami/kafka/config/consumer.properties
      - ${BASE_DIR}/kafka/config/connect-distributed.properties:/opt/bitnami/kafka/config/connect-distributed.properties
      - ${BASE_DIR}/kafka/config/connect-dir-source.properties:/opt/bitnami/kafka/config/connect-dir-source.properties
    ports:
      - '39092:39092'
    depends_on:
      - zookeeper
    networks:
      - app-tier