version: '2'

networks:
  app-tier:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:3.7.1'
    environment:
      ZOO_SERVER_ID: 1
      ZOO_PORT_NUMBER: 2181
      ZOO_TICK_TIME: 2000
      ZOO_INIT_LIMIT: 10
      ZOO_SYNC_LIMIT: 5
      ALLOW_ANONYMOUS_LOGIN: yes
    volumes:
      - ${BASE_DIR}/zookeeper/data:/bitnami
      - ${BASE_DIR}/zookeeper/config/zoo.cfg:/opt/bitnami/zookeeper/conf/zoo.cfg
    ports:
      - '2181:2181'
    networks:
      - app-tier

  kafka:
    image: 'bitnami/kafka:3.4.0'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - ${BASE_DIR}/kafka/data:/bitnami
      - ${BASE_DIR}/kafka/config/server.properties:/opt/bitnami/kafka/config/server.properties
      - ${BASE_DIR}/kafka/config/producer.properties:/opt/bitnami/kafka/config/producer.properties
      - ${BASE_DIR}/kafka/config/consumer.properties:/opt/bitnami/kafka/config/consumer.properties
      - ${BASE_DIR}/kafka/config/connect-standalone.properties:/opt/bitnami/kafka/config/connect-standalone.properties
      - ${BASE_DIR}/kafka/config/connect-file-source.properties:/opt/bitnami/kafka/config/connect-file-source.properties
      - ${BASE_DIR}/kafka/config/connect-dir-source.properties:/opt/bitnami/kafka/config/connect-dir-source.properties
      - ${BASE_DIR}/kafka/config/connect-file-sink.properties:/opt/bitnami/kafka/config/connect-file-sink.properties
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    networks:
      - app-tier